spring.application.name=category-service
server.port=8084

spring.config.import=optional:configserver:http://localhost:8888
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Database Connection (Remember to manually create 'news_categories' in MySQL first!)
spring.datasource.url=jdbc:mysql://localhost:3306/news_comment_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true